<?php
$messages = array(
    "class" => "Class",
    "create-new-class" => "Create a new class",
    "choose-class" => "Please choose a class",
    "choose-cohort" => "Please choose a group",
    "choose-subject" => "Please choose a subject",
    "image" => "Image",
    "in-progress" => "In Progress",
    "join" => "Join",
    "join-class" => "Join Class",
    "joined-class" => "You joined the class.",
    "my-classes" => "My Classes",
    "new-class" => "New Class",
    "new-topic-line" => "New Topic",
    "no-resources-set" => "No resources have been assigned to this class",
    "no-homework-set" => "No homework has been set for this class",
    "no-students-set" => "No students have joined this class",
    "edit-class" => "Edit Class",
    "not-joined" => "Was not possible join in class.",
    "pending" => "Pending",
    "remove-class" => "Remove Class",
    "slots" => "Lessons",
    "select-a-class" => "Please select a class",
    "times" => "Times",
    "class-updated" => "Class was updated.",
    "class-created" => "Class was created.",
    "class-deleted" => "Class was deleted successfully",
    "class-not-found" => "Class was not found",
    "slot-not-saved" => "Lesson was not saved.",
    "slot-not-deleted" => "Lesson was not deleted.",
    "slot-deleted" => "Lesson was deleted by me.",
    "view-all" => "View All",
    "some-new-text-1" => "Here is new text 1",
    "some-new-text-2" => "Here is new text 2"
);
?>
