<?php

$messages = array(
    "user" => "User",
    "name" => "Name",
    "first" => "First",
    "lastname" => "Last",
    "type" => "Type",
    "email" => "Email",
    "Confirm Email" => "Confirm Email",
    "password" => "Password",
    "photo" => "Photo",
    "create" => "Create",
    "Access Code" => "Access Code",
    "Confirm Password" => "Confirm Password",
    "Change your password" => "Change your password",
    "Old Password" => "Old Password",
    "New Password" => "New Password",
    "Confirm New Password" => "Confirm New Password",
    "user-updated" => "user was updated successfully",
    "user-deleted" => "User was deleted",
    "user-not-deleted" => "Was not possible remove the user.",
    "invalid-password" => "invalid password",
    "password-not-changed" => "was not possible to change your password",
    "password-updated" => "password was updated successfully",
    "photo-uploaded" => "The photo was uploaded.",
    "photo-not-uploaded" => "The photo was not uploaded.",
    "Your Information" => "Your Information",
    "Yours School Information" => "Your's School Information",
    "need-confirm-password" => "You need confirm the password",
    "need-confirm-email" => "You need confirm the email",
    "user-created" => "user was created successfully",
    "teacher-title" => "Title"
);
?>