<?php
$messages = array(
    "class" => "Klase",
    "create-new-class" => "Izveidot Jaunu klasi",
    "choose-class" => "Ludzu izvelies klasi",
    "choose-cohort" => "Ludzu izvelies grupu",
    "choose-subject" => "Ludzu izvelies macibu priksmetu",
    "image" => "Bilde",
    "in-progress" => "Processa",
    "join" => "Pieveinoties",
    "join-class" => "Pievinoties klasei",
    "joined-class" => "jus pievienojaties klasei",
    "my-classes" => "Manas klases",
    "new-class" => "Jauna Klase",
    "new-topic-line" => "Jauna kautkas",
    "no-resources-set" => "Nav resursu pierekstiiti sai klasei",
    "no-homework-set" => "Nav majasdzrbu uzdotu sai klasei",
    "no-students-set" => "NAv studentu pievienojushies sai klasei",
    "edit-class" => "Skatiit klasi",
    "not-joined" => "Nebij iespejams pievienoties klasei",
    "pending" => "Ladejas",
    "remove-class" => "Klase nenjemta",
    "slots" => "Nodarbibas",
    "select-a-class" => "Ludzu izvelaties klasi",
    "times" => "Laiki",
    "class-updated" => "Kase bija atjaunota",
    "class-created" => "Kase it izveidota",
    "class-deleted" => "Klase bija veiksmigi izdzesta",
    "class-not-found" => "Klase nav atrasta",
    "slot-not-saved" => "Nòdarbiba nav saglabata",
    "slot-not-deleted" => "Nodarbiba nav izdzesta",
    "slot-deleted" => "sdfsk",
    "view-all" => "Satiits visu",
    "some-new-text-1" => "jhkjh 1",
    "some-new-text-2" => "AKSDj 2"
);
?>
